name = "Tables"
uuid = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
authors = ["quinnj <quinn.jacobd@gmail.com>"]
version = "0.1.14"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
