name = "Tables"
uuid = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
authors = ["quinnj <quinn.jacobd@gmail.com>"]
version = "0.2.11"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DataValueInterfaces = "e2d170a0-9d28-54be-80f0-106bbe20a464"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
QueryOperators = "2aef5ad7-51ca-5a8f-8e88-e75cf067b44b"

[compat]
julia = "1"
IteratorInterfaceExtensions = "0.1.1, 1"
TableTraits = "0.4.1, 1"

[targets]
test = ["Test", "DataValues", "QueryOperators"]
